### ISSUE TITLE
Inclusive boundaries for ordinal limits

### ISSUE THREAD

**Issue by oskar-taubert** [Helmholtz-AI-Energy/propulate#40]
Currently all given limits except categorical ones are exclusive, which might be unexpected for ordinal ones.
Document or make very clear.

**Comment by mcw92** [comment]
Just as a quick overview:
- For continuous parameters of type `float`, we use `random.uniform` to sample new values within limits. According to the official documentation, this function should mostly include the boundaries, for sure the starting point: https://docs.python.org/3/library/random.html#real-valued-distributions
`random.uniform(a, b)`: Return a random floating point number $N$ such that $a <= N <= b$ for $a <= b$ and $b <= N <= a$ for $b < a$. The end-point value $b$ may or may not be included in the range depending on floating-point rounding in the equation $a + (b-a) \cdot random()$.
- For ordinal parameters of type `int`, we use `random.randrange` to sample new values within limits. According to the official documentation, this function does not include the upper boundary: https://docs.python.org/3/library/random.html#functions-for-integers
`random.randrange(start, stop[, step])`: Return a randomly selected element from range(start, stop, step). This is equivalent to choice(range(start, stop, step)), but doesn’t actually build a range object. The positional argument pattern matches that of [range()](https://docs.python.org/3/library/stdtypes.html#range). Keyword arguments should not be used because the function may use them in unexpected ways.
To include both boundaries, we could use `random.randint()` instead:
`random.randint(a, b)`: Return a random integer $N$ such that $a <= N <= b$. Alias for `randrange(a, b+1)`.
- For categorical parameters of type `str`, we use `random.choice` to sample new values within limits. According to the official documentation, this function considers all values in a given sequence: https://docs.python.org/3/library/random.html#functions-for-sequences
`random.choice(seq)`: Return a random element from the non-empty sequence `seq`. If `seq` is empty, raises [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError).

I suggest to make all limit inclusive by changing `random.randrange` to `random.randint` for sampling new values for ordinal parameters within given limits. I will make a new PR for this.
